name: build
on: [ push, workflow_dispatch ]
jobs:
  build:
    name: ${{ matrix.project }}
    runs-on: windows-2022

    strategy:
      matrix:
        project: [foo_musicbrainz64]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Set up vcpkg
      run: |
        vcpkg integrate install
        vcpkg install fmt nlohmann-json wtl --triplet x64-windows

    - name: Create component folder
      run: |
        mkdir component

    - name: Build x64
      run: |
        msbuild src\${{ matrix.project }}.sln -m -p:Platform=x64 -p:Configuration=Release
        copy src\x64\Release\${{ matrix.project }}.dll component
        copy src\x64\Release\${{ matrix.project }}.pdb component

    - name: Upload with pdb
      if: startsWith(github.ref, 'refs/tags')
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.project }}-${{ github.ref_name }}-with-pdb
        path: component

    - name: Delete pdb files and zip for release
      if: startsWith(github.ref, 'refs/tags')
      working-directory: component
      run: |
        del ${{ matrix.project }}.pdb
        7z a -tzip ${{ matrix.project }}-${{ github.ref_name }}.fb2k-component *

    - name: Release
      if: startsWith(github.ref, 'refs/tags')
      uses: softprops/action-gh-release@v1
      with:
        files: component/${{ matrix.project }}-${{ github.ref_name }}.fb2k-component
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
